[package]
name = "air780e-uart-server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.49", features = ["full"] }
tokio-serial = { version = "5.4" }
regex = { version = "1.12" }